import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,act,restore,serialize} from '../src/game.js';import {intent} from '../src/boss.js';
function boss(seed=31,companion='ao'){const s=fresh(seed,{companion});s.phase='battle';s.floor=10;s.enemy={name:'星樹の守り手',hp:90,maxHp:90,turn:0,boss:true,pattern:1};s.strikeRng=1;return s;}
const copy=s=>restore(serialize(s));
test('normal hit precedes warning, guarded heavy precedes one safe opening; reload preserves each intent',()=>{let s=boss();act(s,'attack');assert.equal(intent(s.enemy),'heavy');assert.ok(s.hp>=87);s=copy(s);const hp=s.hp;act(s,'guard');assert.ok(hp-s.hp<=4);assert.equal(intent(s.enemy),'opening');s=copy(s);const before=s.hp;act(s,'skill');assert.equal(s.hp,before);assert.equal(intent(s.enemy),'normal');assert.match(s.log[0],/反撃なし/);});
test('heavy skill weakens only on hit, miss spends focus; opening bonus respects miss/crit/equipment; ward survives',()=>{for(const rng of [1,1972,0]){const a=boss(),b=copy(a);a.enemy.turn=b.enemy.turn=1;a.strikeRng=b.strikeRng=rng;act(a,'skill');act(b,'attack');if(a.lastAttack.kind!=='miss')assert.ok(a.hp>b.hp);assert.equal(a.focus,3);}for(const rng of [1972,1,1800]){const s=boss();s.enemy.turn=2;s.strikeRng=rng;const a=copy(s);a.enemy.pattern=undefined;act(s,'attack');act(a,'attack');assert.equal(s.lastAttack.damage,a.lastAttack.damage+(s.lastAttack.kind==='miss'?0:6));assert.deepEqual(copy(s),s);}const max=boss(31,'ren');max.lastAttack={kind:'critical',damage:54};assert.deepEqual(copy(max),max);const w=boss();w.hp=1;w.ward=1;w.wardFound=true;w.enemy.turn=1;act(w,'attack');assert.equal(w.hp,25);assert.equal(w.ward,0);});
test('old ongoing boss saves keep original schedule; malformed new pattern safely falls back',()=>{const s=boss();delete s.enemy.pattern;s.enemy.turn=1;const restored=copy(s);assert.equal(intent(restored.enemy),'normal');act(restored,'guard');assert.equal(intent(restored.enemy),'heavy');assert.deepEqual(copy(restored),restored);s.enemy.pattern=77;assert.equal(copy(s).enemy.pattern,undefined);});
test('9000 seeded boss comparisons: three companions, spam vs guard/conserve vs skill pressure',()=>{
 for(const companion of ['ao','mei','ren']){const stats={};for(const policy of ['spam','guard','pressure']){let wins=0,hp=0,turns=0,potions=0;for(let seed=0;seed<1000;seed++){let s=boss(seed,companion);delete s.strikeRng;s.hp=70;s.potions=2;let t=0;while(s.phase==='battle'&&t++<40){const phase=intent(s.enemy);let a='attack';if(policy!=='spam'){if(s.hp<28&&s.potions&&(phase==='opening'||phase==='normal'))a='potion';else if(phase==='heavy')a=policy==='pressure'&&s.focus>=3?'skill':'guard';else if(phase==='opening'&&s.focus>=3)a='skill';}act(s,a);s=copy(s);assert.ok(s);}if(s.relic){wins++;hp+=s.hp;}turns+=t;potions+=2-s.potions;}
 stats[policy]={wins,meanHp:Math.round(hp/(wins||1)*10)/10,meanTurns:turns/1000,potions:potions/1000};}console.log('Boss comparison',companion,stats);assert.equal(stats.guard.wins,1000);assert.equal(stats.pressure.wins,1000);assert.ok(stats.guard.meanHp>stats.spam.meanHp);assert.ok(stats.pressure.meanTurns<stats.spam.meanTurns);}
});
