import test from 'node:test';
import assert from 'node:assert/strict';
import {generate,fresh,act,restore,serialize,DIRS,key} from '../src/game.js';
function route(s,to){const q=[[s.x,s.y,[]]],seen=new Set([key(s.x,s.y)]);for(const [x,y,p] of q){if(key(x,y)===key(...to))return p;for(let d=0;d<4;d++){const nx=x+DIRS[d][0],ny=y+DIRS[d][1],k=key(nx,ny);if(s.map.grid[ny]?.[nx]===0&&!seen.has(k)){seen.add(k);q.push([nx,ny,[...p,d]]);}}}throw Error('unreachable');}
function fight(s){for(let turn=0;turn<100&&s.phase==='battle';turn++){if(s.hp<=40&&s.potions)act(s,'potion');else if(s.enemy.turn%3===2)act(s,'guard');else if(s.focus>=3)act(s,'skill');else act(s,'attack');}}
function walk(s,to){for(const d of route(s,to)){while(s.dir!==d)act(s,'right');act(s,'forward');if(s.phase==='battle')fight(s);if(s.phase==='dead')return;}}
test('1500 generated floors: all paths and events reachable, boundaries closed',()=>{for(let seed=0;seed<500;seed++)for(let floor=1;floor<=3;floor++){const map=generate(seed,floor),q=[[1,1]],seen=new Set(['1,1']);for(const [x,y] of q)for(const [dx,dy] of DIRS){const nx=x+dx,ny=y+dy,k=key(nx,ny);if(map.grid[ny]?.[nx]===0&&!seen.has(k)){seen.add(k);q.push([nx,ny]);}}assert.equal(seen.size,map.grid.flat().filter(x=>x===0).length);for(const k of Object.keys(map.events))assert.ok(seen.has(k));assert.ok(seen.has(key(...map.exit)));for(let i=0;i<11;i++)assert.equal(map.grid[0][i]+map.grid[10][i]+map.grid[i][0]+map.grid[i][10],4);assert.deepEqual(map,generate(seed,floor));}});
test('movement, wall collisions, turning, darkness, chest and spring',()=>{const s=fresh(12);s.dir=0;const before=serialize(s);assert.equal(act(s,'forward'),false);assert.equal(s.steps,0);act(s,'right');assert.equal(s.light,100);const d=DIRS.findIndex(([dx,dy])=>s.map.grid[1+dy]?.[1+dx]===0);s.dir=d;const [dx,dy]=DIRS[d],k=key(1+dx,1+dy);s.map.events[k]='chest';act(s,'forward');assert.equal(s.potions,4);assert.ok(s.gold>=18);assert.equal(s.map.events[k],undefined);s.map.events['1,1']='spring';s.hp=20;act(s,'back');assert.equal(s.hp,50);assert.equal(s.focus,6);s.light=0;s.hp=3;act(s,'forward');assert.equal(s.phase,'dead');assert.equal(s.hp,0);assert.equal(act(s,'potion'),false);});
test('battle skills, guard, potion, flee and boss',()=>{const s=fresh(1);const d=DIRS.findIndex(([dx,dy])=>s.map.grid[1+dy]?.[1+dx]===0);s.dir=d;const [dx,dy]=DIRS[d],k=key(1+dx,1+dy);s.map.events[k]='enemy';act(s,'forward');assert.equal(s.phase,'battle');s.focus=0;assert.equal(act(s,'skill'),false);const turn=s.enemy.turn;act(s,'guard');assert.equal(s.focus,2);assert.equal(s.enemy.turn,turn+1);s.hp=30;const potions=s.potions;act(s,'potion');assert.equal(s.potions,potions-1);assert.ok(s.hp>30);act(s,'flee');assert.equal(s.phase,'explore');assert.equal(key(s.x,s.y),'1,1');assert.equal(s.map.events[k],'enemy');s.map.events[k]='shrine';act(s,'forward');assert.equal(act(s,'flee'),false);s.hp=100;s.potions=4;fight(s);assert.equal(s.relic,true);assert.equal(s.phase,'explore');act(s,'return');assert.equal(s.phase,'won');});
test('stairs, extraction, defeat and fresh retry',()=>{const s=fresh(2);s.phase='stairs';const first=s.map;act(s,'stay');assert.equal(s.phase,'explore');s.phase='stairs';s.hp=50;s.light=10;act(s,'descend');assert.equal(s.floor,2);assert.equal(s.hp,68);assert.equal(s.light,35);assert.notDeepEqual(s.map,first);act(s,'return');assert.equal(s.phase,'returned');assert.equal(act(s,'forward'),false);const next=fresh(3);assert.equal(next.floor,1);assert.equal(next.gold,0);assert.equal(next.hp,100);});
test('save round trips exploration and combat; invalid saves rejected',()=>{const s=fresh(9);assert.deepEqual(restore(serialize(s)),s);s.phase='battle';s.enemy={name:'苔角の獣',hp:15,maxHp:25,turn:2,boss:false};assert.deepEqual(restore(serialize(s)),s);for(const raw of [null,'','{','{}','null','{"version":2}',JSON.stringify({...s,hp:-1}),JSON.stringify({...s,map:{}}),JSON.stringify({...s,enemy:null})])assert.equal(restore(raw),null);const a=restore(serialize(s)),b=restore(serialize(s));act(a,'attack');act(b,'attack');assert.deepEqual(a,b);});
test('100 complete expeditions can reach the relic and return using resources',()=>{for(let seed=0;seed<100;seed++){const s=fresh(seed);for(let floor=1;floor<=3;floor++){walk(s,s.map.exit);assert.notEqual(s.phase,'dead',`seed ${seed} floor ${floor}`);if(floor<3){assert.equal(s.phase,'stairs');act(s,'descend');}}assert.equal(s.relic,true,`seed ${seed}`);act(s,'return');assert.equal(s.phase,'won');}});
