import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,act,restore,serialize,DIRS} from '../src/game.js';
import {grantFind,restoreKit} from '../src/loot.js';
const copy=s=>restore(serialize(s));
function fight(companion='mei'){const s=fresh(31,{companion});s.phase='battle';s.enemy={name:'試験',hp:100,maxHp:100,turn:0,boss:false};return s;}
test('run-local finds: one ward, three unique gear, supply duplicates and strict restore',()=>{const s=fresh(21);assert.equal(grantFind(s).kind,'ward');for(let i=0;i<3;i++)assert.equal(grantFind(s).kind,'gear');assert.equal(new Set(s.gearOwned).size,3);const n=s.potions;assert.equal(grantFind(s).kind,'supply');assert.equal(s.potions,n+1);assert.equal(s.ward,1);assert.deepEqual(copy(s),s);const bad={gearOwned:['blade','blade','bad'],equipment:'bad',ward:9};restoreKit(bad);assert.deepEqual(bad.gearOwned,['blade']);assert.equal(bad.equipment,null);assert.equal(bad.ward,0);assert.equal(fresh(21).ward,0);});
test('blade applies only to hitting normal strikes; bark after guard/support; no combat switching',()=>{for(const action of ['attack','skill','guard']){const base=fight('ao'),gear=copy(base);gear.gearOwned=['blade','bark'];gear.equipment='blade';act(base,action);act(gear,action);if(action==='attack')assert.equal(gear.lastAttack.damage-base.lastAttack.damage,base.lastAttack.kind==='miss'?0:2);if(action==='skill')assert.equal(gear.lastAttack.damage,base.lastAttack.damage);assert.equal(act(gear,'equip:bark'),false);}const a=fight('ao'),b=copy(a);b.equipment='bark';act(a,'guard');act(b,'guard');assert.equal(100-b.hp,Math.max(1,100-a.hp-1));});
test('wick saves each fourth step; darkness still hurts, ward triggers once before support',()=>{const s=fresh(2);s.map.events={};s.dir=DIRS.findIndex(([dx,dy])=>s.map.grid[1+dy]?.[1+dx]===0);s.equipment='wick';for(let i=0;i<4;i++)act(s,i%2?'back':'forward');assert.equal(s.light,97);s.light=0;s.hp=3;s.ward=1;s.wardFound=true;act(s,'forward');assert.equal(s.hp,25);assert.equal(s.ward,0);assert.equal(s.lastRescue,true);const saved=copy(s);assert.equal(saved.lastRescue,true);s.hp=3;act(s,'back');assert.equal(s.phase,'dead');const b=fight();b.hp=1;b.ward=1;b.wardFound=true;b.supportCharge=1;act(b,'attack');assert.equal(b.hp,25);assert.equal(b.supportCharge,0);assert.equal(b.ward,0);assert.equal(b.lastRescue,true);});
test('chest receipts survive reload and cannot grant same find twice; old saves receive defaults',()=>{const s=fresh(9);s.dir=DIRS.findIndex(([dx,dy])=>s.map.grid[1+dy]?.[1+dx]===0);const [dx,dy]=DIRS[s.dir],k=`${1+dx},${1+dy}`;s.map.events[k]='chest';act(s,'forward');const restored=copy(s);assert.equal(restored.rewards[0].find.kind,'ward');assert.equal(restored.pendingReward,s.pendingReward);act(restored,'back');restored.map.events[k]='chest';const n=restored.potions;act(restored,'forward');assert.equal(restored.potions,n);assert.equal(restored.gearOwned.length,0);const old=fresh(2,{legacy:true});for(const k of ['gearOwned','equipment','ward','wardFound','lastRescue'])delete old[k];const out=copy(old);assert.deepEqual(out.gearOwned,[]);assert.equal(out.ward,0);});
