import {COMPANIONS} from './companions.js?v=20261003-title-only';
export const GAME_URL='https://monnouchi.github.io/verdant-lantern/';
export function scoreData(s){if(!['won','returned','dead'].includes(s.phase))throw Error('Adventure not finished');return {status:s.phase==='won'?'灯草の種を持ち帰った':s.phase==='returned'?'無事に帰還':'探索終了',companion:COMPANIONS[s.companion]?.name||'ひとりの探索者',floor:s.floor,steps:s.steps,kills:s.kills,score:s.phase==='dead'?0:s.gold,won:s.phase==='won'};}
export function postText(d){return `翠灯の迷宮：${d.status}！ 第${d.floor}層・${d.steps}歩・結晶${d.score}。同行者：${d.companion}`;}
export function xIntent(d){return 'https://x.com/intent/tweet?'+new URLSearchParams({text:postText(d),url:GAME_URL});}
export function drawScore(canvas,d){canvas.width=1080;canvas.height=1080;const c=canvas.getContext('2d');if(!c)throw Error('Canvas unavailable');c.fillStyle='#102b29';c.fillRect(0,0,1080,1080);c.strokeStyle='#a3bf8f';c.lineWidth=3;c.strokeRect(35,35,1010,1010);const text=(t,y,size=40,color='#e8ecd5')=>{c.fillStyle=color;c.font=`600 ${size}px system-ui, sans-serif`;while(c.measureText(t).width>930&&size>18)c.font=`600 ${--size}px system-ui, sans-serif`;c.fillText(t,75,y);};text('翠灯の迷宮',130,68);text(d.status,215,48,'#ead79c');
 c.strokeStyle='#b6d894';c.lineWidth=8;c.beginPath();c.moveTo(865,260);c.lineTo(865,165);c.stroke();c.fillStyle='#b6d894';c.beginPath();c.ellipse(840,198,33,15,.5,0,Math.PI*2);c.ellipse(890,170,33,15,-.5,0,Math.PI*2);c.fill();
 text(`結晶 ${d.score}`,450,90);text(`第${d.floor}層  ·  ${d.steps}歩`,570,46);text(`同行者  ${d.companion}`,665,40);text(`退けた魔物  ${d.kills}体`,740,40);text(d.won?'種から、新しい灯を育てよう。':'帰還の判断も、冒険のうち。',865,32,'#c3d5af');text(GAME_URL,970,28,'#b9cfa7');return canvas;}
export function pngFile(canvas){return new Promise((resolve,reject)=>{try{canvas.toBlob(blob=>blob?resolve(new File([blob],'verdant-lantern-score.png',{type:'image/png'})):reject(Error('PNG unavailable')),'image/png');}catch(e){reject(e);}});}
export function shareSupported(file,nav=navigator){try{return Boolean(nav.share&&nav.canShare?.({files:[file]}));}catch{return false;}}
export async function sendShare(file,d,nav=navigator){try{await nav.share({files:[file],title:'翠灯の迷宮の記録',text:postText(d)+'\n'+GAME_URL});return '共有先へ渡しました。投稿は共有先で確認してください。';}catch(e){return e.name==='AbortError'?'共有を取り消したか、利用できる共有先がありません。記録は変わりません。':'この環境では共有できませんでした。画像保存と投稿文を利用してください。';}}
export function mountShare(root,state){const d=scoreData(state),canvas=root.querySelector('canvas'),status=root.querySelector('[role=status]'),native=root.querySelector('#share-native'),download=root.querySelector('#share-download'),copy=root.querySelector('#share-copy'),text=root.querySelector('textarea');let file=null,url=null,busy=false,disposed=false;text.value=postText(d)+'\n'+GAME_URL;root.querySelector('#share-x').href=xIntent(d);
 copy.onclick=async()=>{try{await navigator.clipboard.writeText(text.value);status.textContent='投稿文をコピーしました。';}catch{status.textContent='コピーできませんでした。下の投稿文を選択してコピーしてください。';text.focus();text.select();}};
 native.onclick=async()=>{if(!file||busy)return;busy=true;native.disabled=true;status.textContent=await sendShare(file,d);if(!disposed){busy=false;native.disabled=false;}};
 (async()=>{try{await document.fonts.ready;if(disposed)return;drawScore(canvas,d);file=await pngFile(canvas);if(disposed)return;url=URL.createObjectURL(file);const preview=root.querySelector('img');if(preview){preview.src=url;preview.hidden=false;canvas.hidden=true;}download.href=url;download.hidden=false;native.hidden=!shareSupported(file);native.disabled=false;status.textContent=native.hidden?'画像を保存し、Xの投稿画面で手動添付できます。':'共有先にXがあれば選べます。画像・本文の扱いは共有先アプリによります。';}catch{status.textContent='画像を作れませんでした。投稿文はコピーできます。';native.hidden=true;}})();
 return ()=>{disposed=true;if(url)URL.revokeObjectURL(url);};
}
